# -*- coding: utf-8 -*-
"""hb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1twbdJaoTHt7D4BzMPR5BWgo-K6aOXn2d
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
!git clone https://github.com/yfszzx/stable-diffusion-webui-images-browser /content/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser
# %pip install -q https://github.com/nolanaatama/sd-webui/releases/download/xformers/xformers-0.0.15+e163309.d20230103-cp38-cp38-linux_x86_64.whl
!curl -Lo hb1.5.1.2.safetensors https://huggingface.co/hassanblend/HassanBlend1.5/resolve/main/HassanBlend1.5.1.2-pruned.safetensors
!curl -Lo hb1.5.1.2.vae.pt https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.ckpt
!mv "/content/hb1.5.1.2.safetensors" "/content/stable-diffusion-webui/models/Stable-diffusion"
!mv "/content/hb1.5.1.2.vae.pt" "/content/stable-diffusion-webui/models/Stable-diffusion"
# %cd /content/stable-diffusion-webui
!git checkout 11d432d # temporary fix
!COMMANDLINE_ARGS="--share --gradio-debug --medvram --disable-safe-unpickle --xformers" REQS_FILE="requirements.txt" python launch.py

from google.colab import drive
drive.mount('/content/drive')

"""# 📚 GitHub for more: [_@nolanaatama_](https://github.com/nolanaatama)
# 📦 Repo: [Github](https://github.com/nolanaatama/sd-hassanblend-colab)
"""